Print errors to stderr

diff --git a/spinmedown b/spinmedown
--- a/spinmedown
+++ b/spinmedown
@@ -13,25 +13,26 @@
 # Root check
 
 if [ "$(id -u)" != "0" ]; then
-  echo "This script must be run with root privileges!"
+  echo "This script must be run with root privileges!" >&2
   exit 1
 fi
 
 echo "** Spinmedown: Spin down a drive if not accessed since the last script call **"
 echo
 
-# The filesystem needs to be given by its UUID; use blkid to figure it out
+# The filesystem needs to be given by its UUID
+
 fsuuid="$1"
 
 if [ -z "$fsuuid" ]; then
-  echo "Error: You need to provide a filesystem UUID as the first parameter!"
+  echo "You need to provide a filesystem UUID as the first parameter!" >&2
   exit 1
 fi
 
 devicefile=$(readlink -f /dev/disk/by-uuid/$fsuuid)
 
 if [ ! -e "$devicefile" ]; then
-  echo "Invalid filesystem UUID! You need to provide it as the first parameter."
+  echo "Invalid filesystem UUID! Please provide one as the first parameter." >&2
   exit 1
 fi
 
@@ -43,7 +44,7 @@ echo "Device name: $devicename"
 statsfile="/sys/block/$devicename/stat"
 
 if [ ! -e "$statsfile" ]; then
-  echo "Invalid device! Please check that you provided a valid filesystem UUID."
+  echo "Invalid device! Please check that you have provided a valid filesystem UUID." >&2
   exit 1
 fi
 
